<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codectest" nsURI="http://example.de/codectest/1.0" nsPrefix="ct">
  <eAnnotations source="Version">
    <details key="value" value="1.0"/>
  </eAnnotations>
  <eAnnotations source="http://geckoprojects.org/codec/1.0.0">
    <details key="name" value="CodecTest"/>
  </eAnnotations>
  <eAnnotations source="foo">
    <details key="bar" value="PersonIdentifier"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Contact">
    <eAnnotations source="foo">
      <details key="name" value="CustomContact"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContactType"
        defaultValueLiteral="Phone"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContactType">
    <eLiterals name="EMAIL" literal="Email"/>
    <eLiterals name="PHONE" value="1" literal="Phone"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DemoDataType" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DemoDataTypeNoSerialize" instanceClassName="java.lang.String"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eAnnotations source="http://geckoprojects.org/codec/1.0.0">
      <details key="name" value="CodecPerson"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="foo">
        <details key="bar" value="PersonIdentifier"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="EMDFirstName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="EMDLastName"/>
      </eAnnotations>
      <eAnnotations source="http://geckoprojects.org/codec/1.0.0">
        <details key="name" value="CodecLastName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="EMDBirthDate"/>
      </eAnnotations>
      <eAnnotations source="http://geckoprojects.org/codec/1.0.0">
        <details key="name" value="CodecBirthDate"/>
      </eAnnotations>
      <eAnnotations source="foo">
        <details key="bar" value="Geburtsdatum"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="#//DemoDataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contacts" lowerBound="1"
        upperBound="-1" eType="#//Contact" containment="true">
      <eAnnotations source="http://geckoprojects.org/codec/1.0.0">
        <details key="name" value="ContactList"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address" eType="#//Address"
        eKeys="#//Address/street #//Address/number #//Address/city #//Address/zip">
      <eAnnotations source="http://geckoprojects.org/codec/1.0.0">
        <details key="name" value="AddressList"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessPerson" eSuperTypes="#//Person">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="EMDBusinessPerson"/>
    </eAnnotations>
    <eAnnotations source="http://geckoprojects.org/codec/1.0.0">
      <details key="name" value="CodecBusinessPerson"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address">
    <eAnnotations source="http://geckoprojects.org/codec/1.0.0">
      <details key="name" value="CodecAddress"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="https://geckoprojects.org/emf/codec/1.0.0">
        <details key="name" value="StreetName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="subpackage" nsURI="http://example.de/codectest/subpackage/1.0"
      nsPrefix="sb">
    <eClassifiers xsi:type="ecore:EClass" name="Example">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exampleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatoryMultiple" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple01" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple02" upperBound="4"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containment" eType="#//Address"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
          transient="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BigLong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BigDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BigInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BigFloat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BigChar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ECharacterObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BigBool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BigShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BigByte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SmallLong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SmallDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SmallInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SmallFloat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SmallChar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SmallBool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SmallShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SmallByte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="foobar" nsURI="http://example.de/codectest/foobar/1.0" nsPrefix="fb">
    <eClassifiers xsi:type="ecore:EClass" name="Foo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
