<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metadata" nsURI="http://www.eclipse.org/fennec/codec/testmetadata"
    nsPrefix="metadata">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="modelDirectory" value="/org.eclipse.fennec.codec.test.models/src"/>
    <details key="updateClasspath" value="false"/>
    <details key="bundleManifest" value="false"/>
    <details key="rootExtendsClass" value="org.eclipse.emf.ecore.impl.MinimalEObjectImpl"/>
    <details key="complianceLevel"/>
    <details key="basePackage" value="org.eclipse.fennec.codec.test.models"/>
    <details key="oSGiCompatible" value="true"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="typeOfPerson"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessPerson" eSuperTypes="#//Person"/>
</ecore:EPackage>
