<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testcodec" nsURI="http://test.codec.example.org/1.0" nsPrefix="testcodec">

  <!-- Simple class without annotations -->
  <eClassifiers xsi:type="ecore:EClass" name="SimpleClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- Class with ID annotation (ID_FIELD strategy) -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonWithIdField">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="idStrategy" value="ID_FIELD"/>
      <details key="idKey" value="_id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with ID annotation (COMBINED strategy) -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonWithCombinedId">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="idStrategy" value="COMBINED"/>
      <details key="idKey" value="_id"/>
      <details key="idSeparator" value="-"/>
      <details key="idFeatures" value="firstName,lastName"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with ID annotation (NONE strategy) -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithNoId">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="idStrategy" value="NONE"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with Type annotation (URI strategy) -->
  <eClassifiers xsi:type="ecore:EClass" name="TypedEntityUri">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="typeStrategy" value="URI"/>
      <details key="typeKey" value="_type"/>
      <details key="typeInclude" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with Type annotation (NAME strategy) -->
  <eClassifiers xsi:type="ecore:EClass" name="TypedEntityName">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="typeStrategy" value="NAME"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with Type annotation (MAPPED strategy) -->
  <eClassifiers xsi:type="ecore:EClass" name="TypedEntityMapped">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="typeStrategy" value="MAPPED"/>
      <details key="typeDiscriminatorPath" value="deviceInfo.profileName"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with Type include=false -->
  <eClassifiers xsi:type="ecore:EClass" name="TypedEntityNoInclude">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="typeInclude" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with SuperType annotation -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithSuperTypes">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="superTypeSerialize" value="true"/>
      <details key="superTypeKey" value="_superTypes"/>
      <details key="superTypeStrategy" value="ALL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with SuperType annotation (SINGLE strategy) -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithSingleSuperType">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="superTypeSerialize" value="true"/>
      <details key="superTypeStrategy" value="SINGLE"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with SuperType annotation (asArray=false) -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithSuperTypesNotAsArray">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="superTypeSerialize" value="true"/>
      <details key="superTypeAsArray" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with SuperType annotation (custom separator) -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithSuperTypesSeparator">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="superTypeSerialize" value="true"/>
      <details key="superTypeAsArray" value="false"/>
      <details key="superTypeSeparator" value="|"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with inherit annotation -->
  <eClassifiers xsi:type="ecore:EClass" name="InheritingEntity">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="inherit" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with discriminator value (using typeMapId) -->
  <eClassifiers xsi:type="ecore:EClass" name="DraginoDevice">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="typeMapId" value="lorawan-dynamic"/>
      <details key="typeDiscriminator" value="Dragino_LSE01"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with custom ID reader/writer -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithCustomIdHandlers">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="idValueReaderName" value="CustomIdReader"/>
      <details key="idValueWriterName" value="CustomIdWriter"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>

  <!-- Class with all configs combined in single annotation -->
  <eClassifiers xsi:type="ecore:EClass" name="FullyConfiguredEntity">
    <eAnnotations source="http://eclipse.org/fennec/codec">
      <details key="idStrategy" value="ID_FIELD"/>
      <details key="typeStrategy" value="URI"/>
      <details key="superTypeSerialize" value="true"/>
      <details key="inherit" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with transient attribute -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithTransientField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secretData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://eclipse.org/fennec/codec">
        <details key="transient" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Class with value reader/writer on attributes -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithCustomValueHandlers">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://eclipse.org/fennec/codec">
        <details key="valueWriterName" value="ISO8601DateWriter"/>
        <details key="valueReaderName" value="FlexibleDateReader"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyWriter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://eclipse.org/fennec/codec">
        <details key="valueWriterName" value="CustomWriter"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyReader" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://eclipse.org/fennec/codec">
        <details key="valueReaderName" value="CustomReader"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Address class for reference testing -->
  <eClassifiers xsi:type="ecore:EClass" name="Address">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class with reference containing type annotation -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonWithTypedReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address" eType="#//Address" containment="true">
      <eAnnotations source="http://eclipse.org/fennec/codec">
        <details key="typeStrategy" value="NAME"/>
        <details key="typeKey" value="_refType"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Class with transient reference -->
  <eClassifiers xsi:type="ecore:EClass" name="EntityWithTransientReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cachedAddress" eType="#//Address">
      <eAnnotations source="http://eclipse.org/fennec/codec">
        <details key="transient" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

</ecore:EPackage>
